services:
  charging-station:
    build: .
    container_name: charging-station
    command: java -cp /app/bin ChargingStationServer
    ports:
      - "1234:1234"
      - "2234:2234"
    environment:
      - RMI_SERVER_HOST=charging-station
    networks:
      - ev-rmi-network

  pricing:
    build: .
    container_name: pricing
    command: java -cp /app/bin PricingServer
    ports:
      - "1238:1238"
      - "2238:2238"
    environment:
      - RMI_SERVER_HOST=pricing
    networks:
      - ev-rmi-network

  reservation:
    build: .
    container_name: reservation
    command: java -cp /app/bin ReservationServer
    ports:
      - "1235:1235"
      - "2235:2235"
    environment:
      - RMI_SERVER_HOST=reservation
      - STATION_HOST=charging-station
    depends_on:
      - charging-station
    networks:
      - ev-rmi-network

  charging-session:
    build: .
    container_name: charging-session
    command: java -cp /app/bin ChargingSessionServer
    ports:
      - "1236:1236"
      - "2236:2236"
    environment:
      - RMI_SERVER_HOST=charging-session
      - STATION_HOST=charging-station
      - RESERVATION_HOST=reservation
    depends_on:
      - charging-station
      - reservation
    networks:
      - ev-rmi-network

  payment:
    build: .
    container_name: payment
    command: java -cp /app/bin PaymentServer
    ports:
      - "1237:1237"
      - "2237:2237"
    environment:
      - RMI_SERVER_HOST=payment
      - STATION_HOST=charging-station
      - SESSION_HOST=charging-session
      - PRICING_HOST=pricing
    depends_on:
      - charging-station
      - charging-session
      - pricing
    networks:
      - ev-rmi-network

networks:
  ev-rmi-network:
    driver: bridge
